/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconsGiftBlue: typeof import('~icons/icons/gift-blue')['default']
    IconsGiftRedSmall: typeof import('~icons/icons/gift-red-small')['default']
    IconsGiftRedTall: typeof import('~icons/icons/gift-red-tall')['default']
    IconsSanta: typeof import('~icons/icons/santa')['default']
    IconsSantaLabel: typeof import('~icons/icons/santa-label')['default']
    IconsTree: typeof import('~icons/icons/tree')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
